//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.24 at 07:17:22 AM CET 
//


package isg.soa.calculator.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the isg.soa.calculator.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: isg.soa.calculator.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultiplicationRequest }
     * 
     */
    public MultiplicationRequest createMultiplicationRequest() {
        return new MultiplicationRequest();
    }

    /**
     * Create an instance of {@link AddRequest }
     * 
     */
    public AddRequest createAddRequest() {
        return new AddRequest();
    }

    /**
     * Create an instance of {@link DivisionResponse }
     * 
     */
    public DivisionResponse createDivisionResponse() {
        return new DivisionResponse();
    }

    /**
     * Create an instance of {@link AddResponse }
     * 
     */
    public AddResponse createAddResponse() {
        return new AddResponse();
    }

    /**
     * Create an instance of {@link MinusRequest }
     * 
     */
    public MinusRequest createMinusRequest() {
        return new MinusRequest();
    }

    /**
     * Create an instance of {@link MunisResponse }
     * 
     */
    public MunisResponse createMunisResponse() {
        return new MunisResponse();
    }

    /**
     * Create an instance of {@link DivisionRequest }
     * 
     */
    public DivisionRequest createDivisionRequest() {
        return new DivisionRequest();
    }

    /**
     * Create an instance of {@link MultipResponse }
     * 
     */
    public MultipResponse createMultipResponse() {
        return new MultipResponse();
    }

}
